name: Javascript Lint with eslint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install js modules.
      run: yarn
    - name: Run ESLint
      run: yarn run eslint .
